### ISSUE TITLE
Cookies are not saved.

### ISSUE THREAD

**Issue by WinnerWind** [samirgaire10/com.samirgaire10.google_gemini-plasma6#1]
As the title says, after a reboot, the plugin forgets all the user data and hence the user needs to sign in again. This can make it annoying for people who use MFA (Multi Factor Authentication) on their accounts. The cookies should be saved, or there should be an option in the plugin settings to save the cookies.
OS : Arch x86_64
KDE Plasma 6.0.4

**Comment by samirgaire10** [comment]
yes the cookie is not saved , and i apologize for  inconvenience .  i tryed to add cookie support but i was unable to do that.

**Comment by samirgaire10** [comment]
if someone can add cookie support then pull request plz

**Comment by Segfault-Git** [comment]
I posted it like kde bug/feature here

https://bugs.kde.org/show_bug.cgi?id=487372

**Comment by samirgaire10** [comment]
Thanks 👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻 Thanks👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

**Comment by samirgaire10** [comment]
now it can save Cookies and other data
